name: "setup"
description: "Setup Node for all workflows"

inputs:
  node_version:
    description: "Version of Node to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: "npm"

    - name: Install Node dependencies
      run: npm ci --prefer-offline
      shell: bash

    - name: Generate syntax files and token patterns
      run: |
        pip install pyyaml
        python3 scripts/generate.py
      shell: bash
